### ISSUE TITLE
adlfs support

### ISSUE THREAD

**Issue by daniel-character** [google/etils#460]
Hey y'all,

Currently you offer support for s3:// (using s3fs) and gs:// (using gcfs). If it's not too much work, could you please add support for az:// aka Azure blob using fsspec's adlfs.

**Comment by Conchylicultor** [comment]
Thank you for the suggestion. With the `fsspec` backend, it should be quite straightforward (using Azure extension for fsspec: https://github.com/fsspec/adlfs)

There's only 3 places to change:

* Add a condition here to load the adlfs fsspec backend:
https://github.com/google/etils/blob/470e1591f2322732832e305fa47c0e95f84e3a90/etils/epath/backend.py#L349

* Add GCS as an accepted URI scheme: https://github.com/google/etils/blob/470e1591f2322732832e305fa47c0e95f84e3a90/etils/epath/gpath.py#L38

* Currently, for backward compatibility, if TF is installed, the `tf.io.gfile` backend will be used instead of `fsspec`. You need to exclude `az://` from this condition that force the TF backend: https://github.com/google/etils/blob/470e1591f2322732832e305fa47c0e95f84e3a90/etils/epath/gpath.py#L110

Don't hesitate to send a PR. Happy to review it.

**Comment by daniel-character** [comment]
Thanks @Conchylicultor. I'm ready to send you a PR. I think I need you to give me the right permissions for that.

**Comment by Conchylicultor** [comment]
> Thanks @Conchylicultor. I'm ready to send you a PR. I think I need you to give me the right permissions for that.

Thanks for the contribution. I'm not sure I understand which permission you need. Everyone is able to send a PR on any repository: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by daniel-character** [comment]
You're right, I just needed a fork. In any case, I just realized something:

So my actual end goal is to make tfds work on az:// paths, and because I'm using tfds via tf.data (instead of using say datasource), tfds actually will read files from the given dataset path via two different paths: etils and tensorflow_io. Unfortunately tensorflow_io expects the az:// path to start with the azure account name, while fsspec does not (it gets the account name from e.g., an env var).

That probably means that if we want tfds to work with az://, I can do all the pieces you suggested excepted this part:

"Currently, for backward compatibility, if TF is installed, the tf.io.gfile backend will be used instead of fsspec. You need to exclude az:// from this condition that force the TF backend".

That way tfds should theoretically be able to work whether you use it with tensorflow or not.

What do you think?

**Comment by Conchylicultor** [comment]
Good for me if that works for you!

**Comment by Conchylicultor** [comment]
https://github.com/google/etils/pull/470 was merged. Closing this! Thanks again for the contribution
